version: "3.9"

services:
  auth-service:
    container_name: auth-service
    image: mondocinema/auth-service:dev
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.production.local
    expose:
      - "9101"
    networks:
      - mondocinema

networks:
  mondocinema:
    external: true
